version: '3.8'
services:
  webapi:
    image: buraktemel/babufirst:latest
    build: 
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:80" 
    environment:
      ASPNETCORE_ENVIRONMENT: Staging 
